---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    curl: :7878/api/system/status
    curl_opts: --header x-api-key:drone
    pipe: |
      jq -r ".version" |
      grep -qw "$(label io.spritsail.version.radarr)"
    run_args: -t -e SUID=0 -e API_KEY=drone
    verbose: true

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    repo: spritsail/radarr
    tags:
    - dotnet
    - '%label io.spritsail.version.radarr | %prefix dotnet'
    login: {from_secret: docker_login}
  when:
    branch:
    - dotnet
    event:
    - push

---
kind: signature
hmac: 13ae7c2ac896a8b062f9b207b752f8607d680336a1cbd8535c34cda6caf5544e

...
