pipeline:
  identify:
    image: docker
    environment:
      - RADARR_BRANCH=develop
    commands:
      # Grab the current version, prevents race conditions
      - apk add --no-cache curl jq
      - set -o pipefail
      - curl -fL "http://radarr.aeonlucid.com/v1/update/$RADARR_BRANCH?os=linux&version=0.0"
            | tee /dev/stderr
            | jq -r '.updatePackage.version' > .radarr_tag

  build:
      image: spritsail/docker-build
      volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
      repo: radarr-dev
      build_args:
        - 'RADARR_TAG=%file: .radarr_tag'

  test:
    image: docker
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      - apk add --no-cache curl
      - CON_NAME=$(docker run -dt -e UID=0 radarr-dev)
      - timeout -t 12 -- docker logs -f $$CON_NAME | cat &
      - sleep 5
      - IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $$CON_NAME)
      - if [ -z "$IP" ]; then
            echo "The container exited.. sadpanda";
            docker inspect --format='{{.State.ExitCode}}' $$CON_NAME;
            docker rm $$CON_NAME
            exit 25;
        fi
      - curl -L --retry-max-time 30 --max-time 5 --retry 10 --retry-delay 5 --retry-connrefused $IP:7878 > /dev/null
      - docker kill $$CON_NAME
      - docker rm $$CON_NAME

  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    when: { event: [ push, tag, deployment ] }
    from: radarr-dev
    repo: spritsail/radarr
    tags:
      - 'latest'
      - '%fileauto: .radarr_tag'
  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
